development:
  adapter: postgresql
  encoding: unicode
  database: nostra_dev
  pool: 5
  username: nostra_dev
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: nostra_prod
  pool: 5
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
